# Generated by Django 4.0.4 on 2025-10-09 16:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Пещера', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Caves', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Пещеру',
                'verbose_name_plural': 'Пещеры',
            },
        ),
        migrations.CreateModel(
            name='Lakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Озеро', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Lakes', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Озеро',
                'verbose_name_plural': 'Озёра',
            },
        ),
        migrations.CreateModel(
            name='Mausoleums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Мавзолей', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Mausoleums', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Мавзолей',
                'verbose_name_plural': 'Мавзолеи',
            },
        ),
        migrations.CreateModel(
            name='Mountains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Гора', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Mountains', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Гору',
                'verbose_name_plural': 'Горы',
            },
        ),
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Геометрия')),
                ('amenity', models.CharField(default='Муниципальный район', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Municipal', editable=False, max_length=255)),
                ('area', models.IntegerField(null=True, verbose_name='Территория')),
            ],
            options={
                'verbose_name': 'Муниципальный район',
                'verbose_name_plural': 'Муниципальные районы',
            },
        ),
        migrations.CreateModel(
            name='Reservoirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Водохранилище', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Reservoirs', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Водохранилище',
                'verbose_name_plural': 'Водохранилища',
            },
        ),
        migrations.CreateModel(
            name='Rocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Скала', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Rocks', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Скалу',
                'verbose_name_plural': 'Скалы',
            },
        ),
        migrations.CreateModel(
            name='Turobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Туристический объект', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Touristsite', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Туристический объект',
                'verbose_name_plural': 'Туристические объекты',
            },
        ),
        migrations.CreateModel(
            name='Waterfalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326, verbose_name='Расположение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип объекта')),
                ('short_description', models.TextField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='Район')),
                ('photo', models.CharField(blank=True, default='', max_length=2000, verbose_name='Фотографии')),
                ('amenity', models.CharField(default='Водопад', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='Waterfalls', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Водопад',
                'verbose_name_plural': 'Водопады',
            },
        ),
    ]
