# Generated by Django 4.0.4 on 2025-10-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turobject',
        ),
        migrations.AlterField(
            model_name='caves',
            name='amenity',
            field=models.CharField(default='Туристический объект', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='caves',
            name='amenity1',
            field=models.CharField(default='Touristsite', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='caves',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='lakes',
            name='amenity',
            field=models.CharField(default='Туристический объект', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='lakes',
            name='amenity1',
            field=models.CharField(default='Touristsite', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='lakes',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='mausoleums',
            name='amenity',
            field=models.CharField(default='Туристический объект', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='mausoleums',
            name='amenity1',
            field=models.CharField(default='Touristsite', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='mausoleums',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='mountains',
            name='amenity',
            field=models.CharField(default='Туристический объект', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='mountains',
            name='amenity1',
            field=models.CharField(default='Touristsite', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='mountains',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='reservoirs',
            name='amenity',
            field=models.CharField(default='Туристический объект', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='reservoirs',
            name='amenity1',
            field=models.CharField(default='Touristsite', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='reservoirs',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='rocks',
            name='amenity',
            field=models.CharField(default='Туристический объект', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='rocks',
            name='amenity1',
            field=models.CharField(default='Touristsite', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='rocks',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='waterfalls',
            name='amenity',
            field=models.CharField(default='Туристический объект', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='waterfalls',
            name='amenity1',
            field=models.CharField(default='Touristsite', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='waterfalls',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Фотографии'),
        ),
    ]
